/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type AllowFingerprinting =
  (typeof AllowFingerprinting)[keyof typeof AllowFingerprinting];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AllowFingerprinting = {
  never: "never",
  newFiles: "newFiles",
  allFiles: "allFiles",
} as const;
