/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type ApplyTags = (typeof ApplyTags)[keyof typeof ApplyTags];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplyTags = {
  add: "add",
  remove: "remove",
  replace: "replace",
} as const;
