/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AddAuthorOptions } from "./addAuthorOptions";
import type { MediaCover } from "./mediaCover";
import type { Book } from "./book";
import type { Links } from "./links";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";
import type { Ratings } from "./ratings";
import type { AuthorStatisticsResource } from "./authorStatisticsResource";
import type { AuthorStatusType } from "./authorStatusType";

export interface AuthorResource {
  added?: string;
  addOptions?: AddAuthorOptions;
  authorMetadataId?: number;
  /** @nullable */
  authorName?: string | null;
  /** @nullable */
  authorNameLastFirst?: string | null;
  /** @nullable */
  cleanName?: string | null;
  /** @nullable */
  disambiguation?: string | null;
  readonly ended?: boolean;
  /** @nullable */
  foreignAuthorId?: string | null;
  /** @nullable */
  genres?: string[] | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  lastBook?: Book;
  /** @nullable */
  links?: Links[] | null;
  metadataProfileId?: number;
  monitored?: boolean;
  monitorNewItems?: NewItemMonitorTypes;
  nextBook?: Book;
  /** @nullable */
  overview?: string | null;
  /** @nullable */
  path?: string | null;
  qualityProfileId?: number;
  ratings?: Ratings;
  /** @nullable */
  remotePoster?: string | null;
  /** @nullable */
  rootFolderPath?: string | null;
  /** @nullable */
  sortName?: string | null;
  /** @nullable */
  sortNameLastFirst?: string | null;
  statistics?: AuthorStatisticsResource;
  status?: AuthorStatusType;
  /** @nullable */
  tags?: number[] | null;
  /** @nullable */
  titleSlug?: string | null;
}
