/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MediaCover } from "./mediaCover";
import type { Links } from "./links";
import type { Ratings } from "./ratings";
import type { AuthorStatusType } from "./authorStatusType";

export interface AuthorMetadata {
  /** @nullable */
  aliases?: string[] | null;
  /** @nullable */
  born?: string | null;
  /** @nullable */
  died?: string | null;
  /** @nullable */
  disambiguation?: string | null;
  /** @nullable */
  foreignAuthorId?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  genres?: string[] | null;
  /** @nullable */
  hometown?: string | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  links?: Links[] | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nameLastFirst?: string | null;
  /** @nullable */
  overview?: string | null;
  ratings?: Ratings;
  /** @nullable */
  sortName?: string | null;
  /** @nullable */
  sortNameLastFirst?: string | null;
  status?: AuthorStatusType;
  /** @nullable */
  titleSlug?: string | null;
}
