/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AddAuthorOptions } from "./addAuthorOptions";
import type { BookListLazyLoaded } from "./bookListLazyLoaded";
import type { AuthorMetadataLazyLoaded } from "./authorMetadataLazyLoaded";
import type { MetadataProfileLazyLoaded } from "./metadataProfileLazyLoaded";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";
import type { QualityProfileLazyLoaded } from "./qualityProfileLazyLoaded";
import type { SeriesListLazyLoaded } from "./seriesListLazyLoaded";

export interface Author {
  added?: string;
  addOptions?: AddAuthorOptions;
  authorMetadataId?: number;
  books?: BookListLazyLoaded;
  /** @nullable */
  cleanName?: string | null;
  /** @nullable */
  foreignAuthorId?: string | null;
  id?: number;
  /** @nullable */
  lastInfoSync?: string | null;
  metadata?: AuthorMetadataLazyLoaded;
  metadataProfile?: MetadataProfileLazyLoaded;
  metadataProfileId?: number;
  monitored?: boolean;
  monitorNewItems?: NewItemMonitorTypes;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  path?: string | null;
  qualityProfile?: QualityProfileLazyLoaded;
  qualityProfileId?: number;
  /** @nullable */
  rootFolderPath?: string | null;
  series?: SeriesListLazyLoaded;
  /** @nullable */
  tags?: number[] | null;
}
