/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ApplyTags } from "./applyTags";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";

export interface AuthorEditorResource {
  applyTags?: ApplyTags;
  /** @nullable */
  authorIds?: number[] | null;
  deleteFiles?: boolean;
  /** @nullable */
  metadataProfileId?: number | null;
  /** @nullable */
  monitored?: boolean | null;
  monitorNewItems?: NewItemMonitorTypes;
  moveFiles?: boolean;
  /** @nullable */
  qualityProfileId?: number | null;
  /** @nullable */
  rootFolderPath?: string | null;
  /** @nullable */
  tags?: number[] | null;
}
