/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type BackupType = (typeof BackupType)[keyof typeof BackupType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BackupType = {
  scheduled: "scheduled",
  manual: "manual",
  update: "update",
} as const;
