/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorResource } from "./authorResource";
import type { CustomFormatResource } from "./customFormatResource";
import type { DownloadProtocol } from "./downloadProtocol";
import type { QualityModel } from "./qualityModel";

export interface BlocklistResource {
  author?: AuthorResource;
  authorId?: number;
  /** @nullable */
  bookIds?: number[] | null;
  /** @nullable */
  customFormats?: CustomFormatResource[] | null;
  date?: string;
  id?: number;
  /** @nullable */
  indexer?: string | null;
  /** @nullable */
  message?: string | null;
  protocol?: DownloadProtocol;
  quality?: QualityModel;
  /** @nullable */
  sourceTitle?: string | null;
}
