/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { BookResource } from "./bookResource";
import type { SortDirection } from "./sortDirection";

export interface BookResourcePagingResource {
  page?: number;
  pageSize?: number;
  /** @nullable */
  records?: BookResource[] | null;
  sortDirection?: SortDirection;
  /** @nullable */
  sortKey?: string | null;
  totalRecords?: number;
}
