/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface BookEditorResource {
  /** @nullable */
  addImportListExclusion?: boolean | null;
  /** @nullable */
  bookIds?: number[] | null;
  /** @nullable */
  deleteFiles?: boolean | null;
  /** @nullable */
  monitored?: boolean | null;
}
