/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorLazyLoaded } from "./authorLazyLoaded";
import type { EditionLazyLoaded } from "./editionLazyLoaded";
import type { IndexerFlags } from "./indexerFlags";
import type { MediaInfoModel } from "./mediaInfoModel";
import type { QualityModel } from "./qualityModel";

export interface BookFile {
  author?: AuthorLazyLoaded;
  calibreId?: number;
  dateAdded?: string;
  edition?: EditionLazyLoaded;
  editionId?: number;
  id?: number;
  indexerFlags?: IndexerFlags;
  mediaInfo?: MediaInfoModel;
  modified?: string;
  /** @nullable */
  originalFilePath?: string | null;
  part?: number;
  partCount?: number;
  /** @nullable */
  path?: string | null;
  quality?: QualityModel;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  sceneName?: string | null;
  size?: number;
}
