/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityModel } from "./qualityModel";

export interface BookFileListResource {
  /** @nullable */
  bookFileIds?: number[] | null;
  quality?: QualityModel;
}
