/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AddBookOptions } from "./addBookOptions";
import type { AuthorResource } from "./authorResource";
import type { EditionResource } from "./editionResource";
import type { MediaCover } from "./mediaCover";
import type { Links } from "./links";
import type { Ratings } from "./ratings";
import type { BookStatisticsResource } from "./bookStatisticsResource";

export interface BookResource {
  /** @nullable */
  added?: string | null;
  addOptions?: AddBookOptions;
  anyEditionOk?: boolean;
  author?: AuthorResource;
  authorId?: number;
  /** @nullable */
  authorTitle?: string | null;
  /** @nullable */
  disambiguation?: string | null;
  /** @nullable */
  editions?: EditionResource[] | null;
  /** @nullable */
  foreignBookId?: string | null;
  /** @nullable */
  foreignEditionId?: string | null;
  /** @nullable */
  genres?: string[] | null;
  grabbed?: boolean;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  links?: Links[] | null;
  monitored?: boolean;
  /** @nullable */
  overview?: string | null;
  pageCount?: number;
  ratings?: Ratings;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  remoteCover?: string | null;
  /** @nullable */
  seriesTitle?: string | null;
  statistics?: BookStatisticsResource;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  titleSlug?: string | null;
}
