/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type BookAddType = (typeof BookAddType)[keyof typeof BookAddType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookAddType = {
  automatic: "automatic",
  manual: "manual",
} as const;
