/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Book } from "./book";

export interface BookListLazyLoaded {
  readonly isLoaded?: boolean;
  /** @nullable */
  readonly value?: readonly Book[] | null;
}
