/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { BookshelfAuthorResource } from "./bookshelfAuthorResource";
import type { MonitoringOptions } from "./monitoringOptions";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";

export interface BookshelfResource {
  /** @nullable */
  authors?: BookshelfAuthorResource[] | null;
  monitoringOptions?: MonitoringOptions;
  monitorNewItems?: NewItemMonitorTypes;
}
