/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AddBookOptions } from "./addBookOptions";
import type { AuthorLazyLoaded } from "./authorLazyLoaded";
import type { AuthorMetadataLazyLoaded } from "./authorMetadataLazyLoaded";
import type { BookFileListLazyLoaded } from "./bookFileListLazyLoaded";
import type { EditionListLazyLoaded } from "./editionListLazyLoaded";
import type { Links } from "./links";
import type { Ratings } from "./ratings";
import type { SeriesBookLinkListLazyLoaded } from "./seriesBookLinkListLazyLoaded";

export interface Book {
  added?: string;
  addOptions?: AddBookOptions;
  anyEditionOk?: boolean;
  author?: AuthorLazyLoaded;
  authorMetadata?: AuthorMetadataLazyLoaded;
  authorMetadataId?: number;
  bookFiles?: BookFileListLazyLoaded;
  /** @nullable */
  cleanTitle?: string | null;
  editions?: EditionListLazyLoaded;
  /** @nullable */
  foreignBookId?: string | null;
  /** @nullable */
  foreignEditionId?: string | null;
  /** @nullable */
  genres?: string[] | null;
  id?: number;
  /** @nullable */
  lastInfoSync?: string | null;
  /** @nullable */
  lastSearchTime?: string | null;
  /** @nullable */
  links?: Links[] | null;
  monitored?: boolean;
  ratings?: Ratings;
  /** @nullable */
  relatedBooks?: number[] | null;
  /** @nullable */
  releaseDate?: string | null;
  seriesLinks?: SeriesBookLinkListLazyLoaded;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  titleSlug?: string | null;
}
