/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ParsedTrackInfo } from "./parsedTrackInfo";
import type { MediaInfoResource } from "./mediaInfoResource";
import type { QualityModel } from "./qualityModel";

export interface BookFileResource {
  audioTags?: ParsedTrackInfo;
  authorId?: number;
  bookId?: number;
  dateAdded?: string;
  id?: number;
  /** @nullable */
  indexerFlags?: number | null;
  mediaInfo?: MediaInfoResource;
  /** @nullable */
  path?: string | null;
  quality?: QualityModel;
  qualityCutoffNotMet?: boolean;
  qualityWeight?: number;
  size?: number;
}
