/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type CertificateValidationType =
  (typeof CertificateValidationType)[keyof typeof CertificateValidationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CertificateValidationType = {
  enabled: "enabled",
  disabledForLocalAddresses: "disabledForLocalAddresses",
  disabled: "disabled",
} as const;
