/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type CommandResult = (typeof CommandResult)[keyof typeof CommandResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommandResult = {
  unknown: "unknown",
  successful: "successful",
  unsuccessful: "unsuccessful",
} as const;
