/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { CustomFilterResourceFiltersItem } from "./customFilterResourceFiltersItem";

export interface CustomFilterResource {
  /** @nullable */
  filters?: CustomFilterResourceFiltersItem[] | null;
  id?: number;
  /** @nullable */
  label?: string | null;
  /** @nullable */
  type?: string | null;
}
