/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { CustomFormatSpecificationSchema } from "./customFormatSpecificationSchema";

export interface CustomFormatResource {
  id?: number;
  /** @nullable */
  includeCustomFormatWhenRenaming?: boolean | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  specifications?: CustomFormatSpecificationSchema[] | null;
}
