/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { DownloadProtocol } from "./downloadProtocol";

export interface DelayProfileResource {
  bypassIfAboveCustomFormatScore?: boolean;
  bypassIfHighestQuality?: boolean;
  enableTorrent?: boolean;
  enableUsenet?: boolean;
  id?: number;
  minimumCustomFormatScore?: number;
  order?: number;
  preferredProtocol?: DownloadProtocol;
  /** @nullable */
  tags?: number[] | null;
  torrentDelay?: number;
  usenetDelay?: number;
}
