/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface DevelopmentConfigResource {
  /** @nullable */
  consoleLogLevel?: string | null;
  filterSentryEvents?: boolean;
  id?: number;
  logRotate?: number;
  logSql?: boolean;
  /** @nullable */
  metadataSource?: string | null;
}
