/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { BookLazyLoaded } from "./bookLazyLoaded";
import type { BookFileListLazyLoaded } from "./bookFileListLazyLoaded";
import type { MediaCover } from "./mediaCover";
import type { Links } from "./links";
import type { Ratings } from "./ratings";

export interface Edition {
  /** @nullable */
  asin?: string | null;
  book?: BookLazyLoaded;
  bookFiles?: BookFileListLazyLoaded;
  bookId?: number;
  /** @nullable */
  disambiguation?: string | null;
  /** @nullable */
  foreignEditionId?: string | null;
  /** @nullable */
  format?: string | null;
  id?: number;
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  isbn13?: string | null;
  isEbook?: boolean;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  links?: Links[] | null;
  manualAdd?: boolean;
  monitored?: boolean;
  /** @nullable */
  overview?: string | null;
  pageCount?: number;
  /** @nullable */
  publisher?: string | null;
  ratings?: Ratings;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  titleSlug?: string | null;
}
