/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Edition } from "./edition";

export interface EditionListLazyLoaded {
  readonly isLoaded?: boolean;
  /** @nullable */
  readonly value?: readonly Edition[] | null;
}
