/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type EntityHistoryEventType =
  (typeof EntityHistoryEventType)[keyof typeof EntityHistoryEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityHistoryEventType = {
  unknown: "unknown",
  grabbed: "grabbed",
  bookFileImported: "bookFileImported",
  downloadFailed: "downloadFailed",
  bookFileDeleted: "bookFileDeleted",
  bookFileRenamed: "bookFileRenamed",
  bookImportIncomplete: "bookImportIncomplete",
  downloadImported: "downloadImported",
  bookFileRetagged: "bookFileRetagged",
  downloadIgnored: "downloadIgnored",
} as const;
