/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ConfigNamingExamplesParams = {
  renameBooks?: boolean;
  replaceIllegalCharacters?: boolean;
  colonReplacementFormat?: number;
  standardBookFormat?: string;
  authorFolderFormat?: string;
  includeAuthorName?: boolean;
  includeBookTitle?: boolean;
  includeQuality?: boolean;
  replaceSpaces?: boolean;
  separator?: string;
  numberStyle?: string;
  id?: number;
  resourceName?: string;
};
