/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ManualimportParams = {
  folder?: string;
  downloadId?: string;
  authorId?: number;
  filterExistingFiles?: boolean;
  replaceExistingFiles?: boolean;
};
