/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { EntityHistoryEventType } from "./entityHistoryEventType";

export type GetApiV1HistorySinceParams = {
  date?: string;
  eventType?: EntityHistoryEventType;
  includeAuthor?: boolean;
  includeBook?: boolean;
};
