/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type HistoryResourceData = { [key: string]: string | null } | null;
