/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorResource } from "./authorResource";
import type { BookResource } from "./bookResource";
import type { CustomFormatResource } from "./customFormatResource";
import type { HistoryResourceData } from "./historyResourceData";
import type { EntityHistoryEventType } from "./entityHistoryEventType";
import type { QualityModel } from "./qualityModel";

export interface HistoryResource {
  author?: AuthorResource;
  authorId?: number;
  book?: BookResource;
  bookId?: number;
  /** @nullable */
  customFormats?: CustomFormatResource[] | null;
  customFormatScore?: number;
  /** @nullable */
  data?: HistoryResourceData;
  date?: string;
  /** @nullable */
  downloadId?: string | null;
  eventType?: EntityHistoryEventType;
  id?: number;
  quality?: QualityModel;
  qualityCutoffNotMet?: boolean;
  /** @nullable */
  sourceTitle?: string | null;
}
