/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface HttpUri {
  /** @nullable */
  readonly fragment?: string | null;
  /** @nullable */
  readonly fullUri?: string | null;
  /** @nullable */
  readonly host?: string | null;
  /** @nullable */
  readonly path?: string | null;
  /** @nullable */
  readonly port?: number | null;
  /** @nullable */
  readonly query?: string | null;
  /** @nullable */
  readonly scheme?: string | null;
}
