/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface ICustomFormatSpecification {
  /** @nullable */
  readonly implementationName?: string | null;
  /** @nullable */
  readonly infoLink?: string | null;
  /** @nullable */
  name?: string | null;
  negate?: boolean;
  readonly order?: number;
  required?: boolean;
}
