/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type ImportListMonitorType =
  (typeof ImportListMonitorType)[keyof typeof ImportListMonitorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImportListMonitorType = {
  none: "none",
  specificBook: "specificBook",
  entireAuthor: "entireAuthor",
} as const;
