/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type IndexerFlags = (typeof IndexerFlags)[keyof typeof IndexerFlags];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexerFlags = {
  freeleech: "freeleech",
  halfleech: "halfleech",
  doubleUpload: "doubleUpload",
  internal: "internal",
  scene: "scene",
  freeleech75: "freeleech75",
  freeleech25: "freeleech25",
} as const;
