/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface IndexerConfigResource {
  id?: number;
  maximumSize?: number;
  minimumAge?: number;
  retention?: number;
  rssSyncInterval?: number;
}
