/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { LogResource } from "./logResource";
import type { SortDirection } from "./sortDirection";

export interface LogResourcePagingResource {
  page?: number;
  pageSize?: number;
  /** @nullable */
  records?: LogResource[] | null;
  sortDirection?: SortDirection;
  /** @nullable */
  sortKey?: string | null;
  totalRecords?: number;
}
