/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ParsedTrackInfo } from "./parsedTrackInfo";
import type { AuthorResource } from "./authorResource";
import type { BookResource } from "./bookResource";
import type { QualityModel } from "./qualityModel";
import type { Rejection } from "./rejection";

export interface ManualImportResource {
  additionalFile?: boolean;
  audioTags?: ParsedTrackInfo;
  author?: AuthorResource;
  book?: BookResource;
  disableReleaseSwitching?: boolean;
  /** @nullable */
  downloadId?: string | null;
  /** @nullable */
  foreignEditionId?: string | null;
  id?: number;
  indexerFlags?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  path?: string | null;
  quality?: QualityModel;
  qualityWeight?: number;
  /** @nullable */
  rejections?: Rejection[] | null;
  /** @nullable */
  releaseGroup?: string | null;
  replaceExistingFiles?: boolean;
  size?: number;
}
