/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { QualityModel } from "./qualityModel";
import type { Rejection } from "./rejection";

export interface ManualImportUpdateResource {
  additionalFile?: boolean;
  /** @nullable */
  authorId?: number | null;
  /** @nullable */
  bookId?: number | null;
  disableReleaseSwitching?: boolean;
  /** @nullable */
  downloadId?: string | null;
  /** @nullable */
  foreignEditionId?: string | null;
  id?: number;
  indexerFlags?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  path?: string | null;
  quality?: QualityModel;
  /** @nullable */
  rejections?: Rejection[] | null;
  /** @nullable */
  releaseGroup?: string | null;
  replaceExistingFiles?: boolean;
}
