/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface MetadataProfileResource {
  /** @nullable */
  allowedLanguages?: string | null;
  id?: number;
  /** @nullable */
  ignored?: string[] | null;
  minPages?: number;
  minPopularity?: number;
  /** @nullable */
  name?: string | null;
  skipMissingDate?: boolean;
  skipMissingIsbn?: boolean;
  skipPartsAndSets?: boolean;
  skipSeriesSecondary?: boolean;
}
