/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MetadataProfile } from "./metadataProfile";

export interface MetadataProfileLazyLoaded {
  readonly isLoaded?: boolean;
  value?: MetadataProfile;
}
