/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { WriteAudioTagsType } from "./writeAudioTagsType";
import type { WriteBookTagsType } from "./writeBookTagsType";

export interface MetadataProviderConfigResource {
  embedMetadata?: boolean;
  id?: number;
  scrubAudioTags?: boolean;
  updateCovers?: boolean;
  writeAudioTags?: WriteAudioTagsType;
  writeBookTags?: WriteBookTagsType;
}
