/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface NamingConfigResource {
  /** @nullable */
  authorFolderFormat?: string | null;
  colonReplacementFormat?: number;
  id?: number;
  includeAuthorName?: boolean;
  includeBookTitle?: boolean;
  includeQuality?: boolean;
  /** @nullable */
  numberStyle?: string | null;
  renameBooks?: boolean;
  replaceIllegalCharacters?: boolean;
  replaceSpaces?: boolean;
  /** @nullable */
  separator?: string | null;
  /** @nullable */
  standardBookFormat?: string | null;
}
