/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type NewItemMonitorTypes =
  (typeof NewItemMonitorTypes)[keyof typeof NewItemMonitorTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewItemMonitorTypes = {
  all: "all",
  none: "none",
  new: "new",
} as const;
