/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Field } from "./field";
import type { ProviderMessage } from "./providerMessage";

export interface NotificationResource {
  /** @nullable */
  configContract?: string | null;
  /** @nullable */
  fields?: Field[] | null;
  id?: number;
  /** @nullable */
  implementation?: string | null;
  /** @nullable */
  implementationName?: string | null;
  includeHealthWarnings?: boolean;
  /** @nullable */
  infoLink?: string | null;
  /** @nullable */
  link?: string | null;
  message?: ProviderMessage;
  /** @nullable */
  name?: string | null;
  onApplicationUpdate?: boolean;
  onAuthorAdded?: boolean;
  onAuthorDelete?: boolean;
  onBookDelete?: boolean;
  onBookFileDelete?: boolean;
  onBookFileDeleteForUpgrade?: boolean;
  onBookRetag?: boolean;
  onDownloadFailure?: boolean;
  onGrab?: boolean;
  onHealthIssue?: boolean;
  onImportFailure?: boolean;
  onReleaseImport?: boolean;
  onRename?: boolean;
  onUpgrade?: boolean;
  /** @nullable */
  presets?: NotificationResource[] | null;
  supportsOnApplicationUpdate?: boolean;
  supportsOnAuthorAdded?: boolean;
  supportsOnAuthorDelete?: boolean;
  supportsOnBookDelete?: boolean;
  supportsOnBookFileDelete?: boolean;
  supportsOnBookFileDeleteForUpgrade?: boolean;
  supportsOnBookRetag?: boolean;
  supportsOnDownloadFailure?: boolean;
  supportsOnGrab?: boolean;
  supportsOnHealthIssue?: boolean;
  supportsOnImportFailure?: boolean;
  supportsOnReleaseImport?: boolean;
  supportsOnRename?: boolean;
  supportsOnUpgrade?: boolean;
  /** @nullable */
  tags?: number[] | null;
  /** @nullable */
  testCommand?: string | null;
}
