/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { IsoCountry } from "./isoCountry";
import type { TimeSpan } from "./timeSpan";
import type { MediaInfoModel } from "./mediaInfoModel";
import type { QualityModel } from "./qualityModel";

export interface ParsedTrackInfo {
  /** @nullable */
  asin?: string | null;
  /** @nullable */
  authorMBId?: string | null;
  /** @nullable */
  authors?: string[] | null;
  /** @nullable */
  readonly authorTitle?: string | null;
  /** @nullable */
  bookMBId?: string | null;
  /** @nullable */
  bookTitle?: string | null;
  /** @nullable */
  catalogNumber?: string | null;
  /** @nullable */
  cleanTitle?: string | null;
  country?: IsoCountry;
  /** @nullable */
  disambiguation?: string | null;
  discCount?: number;
  discNumber?: number;
  duration?: TimeSpan;
  /** @nullable */
  goodreadsId?: string | null;
  /** @nullable */
  isbn?: string | null;
  /** @nullable */
  label?: string | null;
  /** @nullable */
  language?: string | null;
  mediaInfo?: MediaInfoModel;
  /** @nullable */
  publisher?: string | null;
  quality?: QualityModel;
  /** @nullable */
  recordingMBId?: string | null;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  releaseHash?: string | null;
  /** @nullable */
  releaseMBId?: string | null;
  /** @nullable */
  seriesIndex?: string | null;
  /** @nullable */
  seriesTitle?: string | null;
  /** @nullable */
  source?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  trackMBId?: string | null;
  /** @nullable */
  trackNumbers?: number[] | null;
  year?: number;
}
