/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorTitleInfo } from "./authorTitleInfo";
import type { QualityModel } from "./qualityModel";

export interface ParsedBookInfo {
  /** @nullable */
  authorName?: string | null;
  authorTitleInfo?: AuthorTitleInfo;
  /** @nullable */
  bookTitle?: string | null;
  discography?: boolean;
  discographyEnd?: number;
  discographyStart?: number;
  quality?: QualityModel;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  releaseGroup?: string | null;
  /** @nullable */
  releaseHash?: string | null;
  /** @nullable */
  releaseTitle?: string | null;
  /** @nullable */
  releaseVersion?: string | null;
}
