/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorResource } from "./authorResource";
import type { BookResource } from "./bookResource";
import type { ParsedBookInfo } from "./parsedBookInfo";

export interface ParseResource {
  author?: AuthorResource;
  /** @nullable */
  books?: BookResource[] | null;
  id?: number;
  parsedBookInfo?: ParsedBookInfo;
  /** @nullable */
  title?: string | null;
}
