/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileFormatItem } from "./profileFormatItem";
import type { QualityProfileQualityItem } from "./qualityProfileQualityItem";

export interface QualityProfile {
  cutoff?: number;
  cutoffFormatScore?: number;
  /** @nullable */
  formatItems?: ProfileFormatItem[] | null;
  id?: number;
  /** @nullable */
  items?: QualityProfileQualityItem[] | null;
  minFormatScore?: number;
  /** @nullable */
  name?: string | null;
  upgradeAllowed?: boolean;
}
