/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Quality } from "./quality";
import type { Revision } from "./revision";

export interface QualityModel {
  quality?: Quality;
  revision?: Revision;
}
