/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface RemotePathMappingResource {
  /** @nullable */
  host?: string | null;
  id?: number;
  /** @nullable */
  localPath?: string | null;
  /** @nullable */
  remotePath?: string | null;
}
