/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface RenameBookResource {
  authorId?: number;
  bookFileId?: number;
  bookId?: number;
  /** @nullable */
  existingPath?: string | null;
  id?: number;
  /** @nullable */
  newPath?: string | null;
}
