/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { TagDifference } from "./tagDifference";

export interface RetagBookResource {
  authorId?: number;
  bookFileId?: number;
  bookId?: number;
  /** @nullable */
  changes?: TagDifference[] | null;
  id?: number;
  /** @nullable */
  path?: string | null;
  /** @nullable */
  trackNumbers?: number[] | null;
}
