/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AuthorResource } from "./authorResource";
import type { BookResource } from "./bookResource";

export interface SearchResource {
  author?: AuthorResource;
  book?: BookResource;
  /** @nullable */
  foreignId?: string | null;
  id?: number;
}
