/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { SeriesBookLink } from "./seriesBookLink";

export interface SeriesBookLinkListLazyLoaded {
  readonly isLoaded?: boolean;
  /** @nullable */
  readonly value?: readonly SeriesBookLink[] | null;
}
