/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { Series } from "./series";

export interface SeriesListLazyLoaded {
  readonly isLoaded?: boolean;
  /** @nullable */
  readonly value?: readonly Series[] | null;
}
