/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { BookLazyLoaded } from "./bookLazyLoaded";
import type { SeriesLazyLoaded } from "./seriesLazyLoaded";

export interface SeriesBookLink {
  book?: BookLazyLoaded;
  bookId?: number;
  id?: number;
  isPrimary?: boolean;
  /** @nullable */
  position?: string | null;
  series?: SeriesLazyLoaded;
  seriesId?: number;
  seriesPosition?: number;
}
