/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { SeriesBookLinkResource } from "./seriesBookLinkResource";

export interface SeriesResource {
  /** @nullable */
  description?: string | null;
  id?: number;
  /** @nullable */
  links?: SeriesBookLinkResource[] | null;
  /** @nullable */
  title?: string | null;
}
