/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface UiConfigResource {
  /** @nullable */
  calendarWeekColumnHeader?: string | null;
  enableColorImpairedMode?: boolean;
  firstDayOfWeek?: number;
  id?: number;
  /** @nullable */
  longDateFormat?: string | null;
  /** @nullable */
  shortDateFormat?: string | null;
  showRelativeDates?: boolean;
  /** @nullable */
  theme?: string | null;
  /** @nullable */
  timeFormat?: string | null;
  uiLanguage?: number;
}
