/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Readarr
 * Readarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface Version {
  readonly build?: number;
  readonly major?: number;
  readonly majorRevision?: number;
  readonly minor?: number;
  readonly minorRevision?: number;
  readonly revision?: number;
}
