/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumResource } from "./albumResource";

export interface AlbumStudioArtistResource {
  /** @nullable */
  albums?: AlbumResource[] | null;
  id?: number;
  /** @nullable */
  monitored?: boolean | null;
}
