/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumStudioArtistResource } from "./albumStudioArtistResource";
import type { MonitoringOptions } from "./monitoringOptions";
import type { NewItemMonitorTypes } from "./newItemMonitorTypes";

export interface AlbumStudioResource {
  /** @nullable */
  artist?: AlbumStudioArtistResource[] | null;
  monitoringOptions?: MonitoringOptions;
  monitorNewItems?: NewItemMonitorTypes;
}
