/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface ArtistStatisticsResource {
  albumCount?: number;
  readonly percentOfTracks?: number;
  sizeOnDisk?: number;
  totalTrackCount?: number;
  trackCount?: number;
  trackFileCount?: number;
}
