/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type AuthenticationRequiredType =
  (typeof AuthenticationRequiredType)[keyof typeof AuthenticationRequiredType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthenticationRequiredType = {
  enabled: "enabled",
  disabledForLocalAddresses: "disabledForLocalAddresses",
} as const;
