/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type DatabaseType = (typeof DatabaseType)[keyof typeof DatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseType = {
  sqLite: "sqLite",
  postgreSQL: "postgreSQL",
} as const;
