/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface DownloadClientConfigResource {
  autoRedownloadFailed?: boolean;
  autoRedownloadFailedFromInteractiveSearch?: boolean;
  /** @nullable */
  downloadClientWorkingFolders?: string | null;
  enableCompletedDownloadHandling?: boolean;
  id?: number;
}
