/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { SortDirection } from "./sortDirection";
import type { DownloadProtocol } from "./downloadProtocol";

export type GetApiV1QueueParams = {
  page?: number;
  pageSize?: number;
  sortKey?: string;
  sortDirection?: SortDirection;
  includeUnknownArtistItems?: boolean;
  includeArtist?: boolean;
  includeAlbum?: boolean;
  artistIds?: number[];
  protocol?: DownloadProtocol;
  quality?: number;
};
