/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ConfigNamingExamplesParams = {
  renameTracks?: boolean;
  replaceIllegalCharacters?: boolean;
  colonReplacementFormat?: number;
  standardTrackFormat?: string;
  multiDiscTrackFormat?: string;
  artistFolderFormat?: string;
  includeArtistName?: boolean;
  includeAlbumTitle?: boolean;
  includeQuality?: boolean;
  replaceSpaces?: boolean;
  separator?: string;
  numberStyle?: string;
  id?: number;
  resourceName?: string;
};
