/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { SortDirection } from "./sortDirection";

export type GetApiV1HistoryParams = {
  page?: number;
  pageSize?: number;
  sortKey?: string;
  sortDirection?: SortDirection;
  includeArtist?: boolean;
  includeAlbum?: boolean;
  includeTrack?: boolean;
  eventType?: number[];
  albumId?: number;
  downloadId?: string;
  artistIds?: number[];
  quality?: number[];
};
