/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { HistoryResource } from "./historyResource";
import type { SortDirection } from "./sortDirection";

export interface HistoryResourcePagingResource {
  page?: number;
  pageSize?: number;
  /** @nullable */
  records?: HistoryResource[] | null;
  sortDirection?: SortDirection;
  /** @nullable */
  sortKey?: string | null;
  totalRecords?: number;
}
