/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { LocalizationResourceStrings } from "./localizationResourceStrings";

export interface LocalizationResource {
  id?: number;
  /** @nullable */
  strings?: LocalizationResourceStrings;
}
