/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface MediaInfoModel {
  audioBitrate?: number;
  audioBits?: number;
  audioChannels?: number;
  /** @nullable */
  audioFormat?: string | null;
  audioSampleRate?: number;
}
