/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { MediaCover } from "./mediaCover";

export interface Member {
  /** @nullable */
  images?: MediaCover[] | null;
  /** @nullable */
  instrument?: string | null;
  /** @nullable */
  name?: string | null;
}
