/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { WriteAudioTagsType } from "./writeAudioTagsType";

export interface MetadataProviderConfigResource {
  embedCoverArt?: boolean;
  id?: number;
  /** @nullable */
  metadataSource?: string | null;
  scrubAudioTags?: boolean;
  writeAudioTags?: WriteAudioTagsType;
}
