/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumResource } from "./albumResource";
import type { ArtistResource } from "./artistResource";
import type { CustomFormatResource } from "./customFormatResource";
import type { ParsedAlbumInfo } from "./parsedAlbumInfo";

export interface ParseResource {
  /** @nullable */
  albums?: AlbumResource[] | null;
  artist?: ArtistResource;
  /** @nullable */
  customFormats?: CustomFormatResource[] | null;
  customFormatScore?: number;
  id?: number;
  parsedAlbumInfo?: ParsedAlbumInfo;
  /** @nullable */
  title?: string | null;
}
