/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export type PrivacyLevel = (typeof PrivacyLevel)[keyof typeof PrivacyLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrivacyLevel = {
  normal: "normal",
  password: "password",
  apiKey: "apiKey",
  userName: "userName",
} as const;
