/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Lidarr
 * Lidarr API docs
 * OpenAPI spec version: 1.0.0
 */

export interface RenameTrackResource {
  albumId?: number;
  artistId?: number;
  /** @nullable */
  existingPath?: string | null;
  id?: number;
  /** @nullable */
  newPath?: string | null;
  trackFileId?: number;
  /** @nullable */
  trackNumbers?: number[] | null;
}
